### ISSUE TITLE
Could it add an option to disable update?

### ISSUE THREAD

**Issue by smartmadio** [CyR1en/CommandPrompter#1]
`[09:07:03] [Server thread/INFO]: [CommandPrompter] Enabling CommandPrompter v0.1.7
[09:07:33] [Server thread/WARN]: [CommandPrompter] Error querying update data for 'CommandPrompter'!
[09:07:33] [Server thread/WARN]: [CommandPrompter] Error: 
java.net.SocketTimeoutException: connect timed out
	at java.net.PlainSocketImpl.socketConnect(Native Method) ~[?:1.8.0_171]
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350) ~[?:1.8.0_171]
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206) ~[?:1.8.0_171]
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188) ~[?:1.8.0_171]
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392) ~[?:1.8.0_171]
	at java.net.Socket.connect(Socket.java:589) ~[?:1.8.0_171]
	at sun.security.ssl.SSLSocketImpl.connect(SSLSocketImpl.java:673) ~[?:1.8.0_171]
	at sun.net.NetworkClient.doConnect(NetworkClient.java:175) ~[?:1.8.0_171]
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:463) ~[?:1.8.0_171]
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:558) ~[?:1.8.0_171]
	at sun.net.www.protocol.https.HttpsClient.<init>(HttpsClient.java:264) ~[?:1.8.0_171]
	at sun.net.www.protocol.https.HttpsClient.New(HttpsClient.java:367) ~[?:1.8.0_171]
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(AbstractDelegateHttpsURLConnection.java:191) ~[?:1.8.0_171]
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1156) ~[?:1.8.0_171]
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1050) ~[?:1.8.0_171]
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:177) ~[?:1.8.0_171]
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.connect(HttpsURLConnectionImpl.java:162) ~[?:1.8.0_171]
	at org.jsoup.helper.HttpConnection$Response.execute(HttpConnection.java:746) ~[CommandPrompter-0.1.7.jar:0.1.7]
	at org.jsoup.helper.HttpConnection$Response.execute(HttpConnection.java:722) ~[CommandPrompter-0.1.7.jar:0.1.7]
	at org.jsoup.helper.HttpConnection.execute(HttpConnection.java:306) ~[CommandPrompter-0.1.7.jar:0.1.7]
	at org.jsoup.helper.HttpConnection.get(HttpConnection.java:295) ~[CommandPrompter-0.1.7.jar:0.1.7]
	at com.cyr1en.cp.util.PluginUpdater.queryUpdateData(PluginUpdater.java:61) [CommandPrompter-0.1.7.jar:0.1.7]
	at com.cyr1en.cp.util.PluginUpdater.needsUpdate(PluginUpdater.java:73) [CommandPrompter-0.1.7.jar:0.1.7]
	at com.cyr1en.cp.CommandPrompter.onEnable(CommandPrompter.java:24) [CommandPrompter-0.1.7.jar:0.1.7]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) [patched_1.12.2.jar:git-Paper-1418]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:316) [patched_1.12.2.jar:git-Paper-1418]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) [patched_1.12.2.jar:git-Paper-1418]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:395) [patched_1.12.2.jar:git-Paper-1418]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:344) [patched_1.12.2.jar:git-Paper-1418]
	at net.minecraft.server.v1_12_R1.MinecraftServer.t(MinecraftServer.java:442) [patched_1.12.2.jar:git-Paper-1418]
	at net.minecraft.server.v1_12_R1.MinecraftServer.l(MinecraftServer.java:403) [patched_1.12.2.jar:git-Paper-1418]
	at net.minecraft.server.v1_12_R1.MinecraftServer.a(MinecraftServer.java:341) [patched_1.12.2.jar:git-Paper-1418]
	at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:293) [patched_1.12.2.jar:git-Paper-1418]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:616) [patched_1.12.2.jar:git-Paper-1418]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_171]
[09:08:03] [Server thread/WARN]: [CommandPrompter] Error querying update data for 'CommandPrompter'!
[09:08:03] [Server thread/WARN]: [CommandPrompter] Error: 
java.net.SocketTimeoutException: connect timed out
	at java.net.PlainSocketImpl.socketConnect(Native Method) ~[?:1.8.0_171]
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350) ~[?:1.8.0_171]
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206) ~[?:1.8.0_171]
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188) ~[?:1.8.0_171]
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392) ~[?:1.8.0_171]
	at java.net.Socket.connect(Socket.java:589) ~[?:1.8.0_171]
	at sun.security.ssl.SSLSocketImpl.connect(SSLSocketImpl.java:673) ~[?:1.8.0_171]
	at sun.net.NetworkClient.doConnect(NetworkClient.java:175) ~[?:1.8.0_171]
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:463) ~[?:1.8.0_171]
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:558) ~[?:1.8.0_171]
	at sun.net.www.protocol.https.HttpsClient.<init>(HttpsClient.java:264) ~[?:1.8.0_171]
	at sun.net.www.protocol.https.HttpsClient.New(HttpsClient.java:367) ~[?:1.8.0_171]
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(AbstractDelegateHttpsURLConnection.java:191) ~[?:1.8.0_171]
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1156) ~[?:1.8.0_171]
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1050) ~[?:1.8.0_171]
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:177) ~[?:1.8.0_171]
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.connect(HttpsURLConnectionImpl.java:162) ~[?:1.8.0_171]
	at org.jsoup.helper.HttpConnection$Response.execute(HttpConnection.java:746) ~[CommandPrompter-0.1.7.jar:0.1.7]
	at org.jsoup.helper.HttpConnection$Response.execute(HttpConnection.java:722) ~[CommandPrompter-0.1.7.jar:0.1.7]
	at org.jsoup.helper.HttpConnection.execute(HttpConnection.java:306) ~[CommandPrompter-0.1.7.jar:0.1.7]
	at org.jsoup.helper.HttpConnection.get(HttpConnection.java:295) ~[CommandPrompter-0.1.7.jar:0.1.7]
	at com.cyr1en.cp.util.PluginUpdater.queryUpdateData(PluginUpdater.java:61) [CommandPrompter-0.1.7.jar:0.1.7]
	at com.cyr1en.cp.util.PluginUpdater.newVersionAvailable(PluginUpdater.java:89) [CommandPrompter-0.1.7.jar:0.1.7]
	at com.cyr1en.cp.util.PluginUpdater.needsUpdate(PluginUpdater.java:76) [CommandPrompter-0.1.7.jar:0.1.7]
	at com.cyr1en.cp.CommandPrompter.onEnable(CommandPrompter.java:24) [CommandPrompter-0.1.7.jar:0.1.7]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) [patched_1.12.2.jar:git-Paper-1418]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:316) [patched_1.12.2.jar:git-Paper-1418]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) [patched_1.12.2.jar:git-Paper-1418]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:395) [patched_1.12.2.jar:git-Paper-1418]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:344) [patched_1.12.2.jar:git-Paper-1418]
	at net.minecraft.server.v1_12_R1.MinecraftServer.t(MinecraftServer.java:442) [patched_1.12.2.jar:git-Paper-1418]
	at net.minecraft.server.v1_12_R1.MinecraftServer.l(MinecraftServer.java:403) [patched_1.12.2.jar:git-Paper-1418]
	at net.minecraft.server.v1_12_R1.MinecraftServer.a(MinecraftServer.java:341) [patched_1.12.2.jar:git-Paper-1418]
	at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:293) [patched_1.12.2.jar:git-Paper-1418]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:616) [patched_1.12.2.jar:git-Paper-1418]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_171]
[09:08:03] [Server thread/ERROR]: Error occurred while enabling CommandPrompter v0.1.7 (Is it up to date?)
java.lang.NullPointerException: null
	at com.cyr1en.cp.util.PluginUpdater.newVersionAvailable(PluginUpdater.java:91) ~[?:?]
	at com.cyr1en.cp.util.PluginUpdater.needsUpdate(PluginUpdater.java:76) ~[?:?]
	at com.cyr1en.cp.CommandPrompter.onEnable(CommandPrompter.java:24) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[patched_1.12.2.jar:git-Paper-1418]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:316) [patched_1.12.2.jar:git-Paper-1418]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) [patched_1.12.2.jar:git-Paper-1418]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:395) [patched_1.12.2.jar:git-Paper-1418]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:344) [patched_1.12.2.jar:git-Paper-1418]
	at net.minecraft.server.v1_12_R1.MinecraftServer.t(MinecraftServer.java:442) [patched_1.12.2.jar:git-Paper-1418]
	at net.minecraft.server.v1_12_R1.MinecraftServer.l(MinecraftServer.java:403) [patched_1.12.2.jar:git-Paper-1418]
	at net.minecraft.server.v1_12_R1.MinecraftServer.a(MinecraftServer.java:341) [patched_1.12.2.jar:git-Paper-1418]
	at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:293) [patched_1.12.2.jar:git-Paper-1418]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:616) [patched_1.12.2.jar:git-Paper-1418]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_171]
[09:08:03] [Server thread/INFO]: [CommandPrompter] Disabling CommandPrompter v0.1.7`

Server version:Paper(1418) 1.12.2-R0.1-SNAPSHOT

Java version:Java8

**Comment by CyR1en** [comment]
This was an issue with the SSL certificate for my domain, But I will add a feature to disable update notification

**Comment by CyR1en** [comment]
Plugin does not automatically update, just checks.

### Added ability to disable update checks
