### ISSUE TITLE
Anvil GUI not opening

### ISSUE THREAD

**Issue by antjparsons** [CyR1en/CommandPrompter#21]
I'm sure an update is coming in future, but in case it gets missed, the only issue spotted so far in 1.18.2 is the anvil GUI not opening. Following exception in console:

[18:41:24 INFO]: player issued server command: /pay <-p Who?> <-a How much?>
[18:41:27 WARN]: [CommandPrompter] Task #6638 for CommandPrompter v0.1.26 generated an exception
java.lang.NoClassDefFoundError: Could not initialize class net.wesjd.anvilgui.AnvilGUI
        at net.wesjd.anvilgui.AnvilGUI$Builder.open(AnvilGUI.java:491) ~[CommandPrompter-0.1.26-SNAPSHOT.jar:?]
        at com.cyr1en.commandprompter.prompt.prompts.AnvilPrompt.sendPrompt(AnvilPrompt.java:53) ~[CommandPrompter-0.1.26-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_18_R2.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.18.2.jar:git-Paper-242]
        at org.bukkit.craftbukkit.v1_18_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483) ~[paper-1.18.2.jar:git-Paper-242]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1535) ~[paper-1.18.2.jar:git-Paper-242]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:483) ~[paper-1.18.2.jar:git-Paper-242]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1458) ~[paper-1.18.2.jar:git-Paper-242]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1227) ~[paper-1.18.2.jar:git-Paper-242]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317) ~[paper-1.18.2.jar:git-Paper-242]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]

Am relying on the signGUI for now :).

**Comment by CyR1en** [comment]
Fixed on newest release: [0.1.27](https://github.com/CyR1en/CommandPrompter/releases/tag/0.1.27)
