### ISSUE TITLE
ConcurrentModificationException on Plugin disable

### ISSUE THREAD

**Issue by CyR1en** [CyR1en/CommandPrompter#3]
```
>.... [14:56:19 ERROR]: Error occurred while disabling CommandPrompter v0.1.17 (Is it up to date?)
java.util.ConcurrentModificationException: null
at java.util.ArrayList.forEach(ArrayList.java:1260) ~[?:1.8.0_212]
at java.util.Collections$UnmodifiableCollection.forEach(Collections.java:1080) ~[?:1.8.0_212]
at com.cyr1en.cp.CommandPrompter.onDisable(CommandPrompter.java:49) ~[?:?]
at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:265) ~[patched_1.14.4.jar:git-Paper-238]
at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:373) ~[patched_1.14.4.jar:git-Paper-238]
at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:453) ~[patched_1.14.4.jar:git-Paper-238]
at org.bukkit.plugin.SimplePluginManager.disablePlugins(SimplePluginManager.java:439) ~[patched_1.14.4.jar:git-Paper-238]
at org.bukkit.plugin.SimplePluginManager.disablePlugins(SimplePluginManager.java:432) ~[patched_1.14.4.jar:git-Paper-238]
at org.bukkit.craftbukkit.v1_14_R1.CraftServer.disablePlugins(CraftServer.java:401) ~[patched_1.14.4.jar:git-Paper-238]
at net.minecraft.server.v1_14_R1.MinecraftServer.stop(MinecraftServer.java:733) ~[patched_1.14.4.jar:git-Paper-238]
at net.minecraft.server.v1_14_R1.DedicatedServer.stop(DedicatedServer.java:739) ~[patched_1.14.4.jar:git-Paper-238]
at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:966) ~[patched_1.14.4.jar:git-Paper-238]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]
```

## Cause

`CommandPrompter#onDisable()` does not check if List `registeredPrompts` is not null.

```java
 @Override
  public void onDisable() {
    Collections.unmodifiableList(registeredPrompts).forEach(this::deregisterPrompt);
  }
```

**Comment by CyR1en** [comment]
Fixed with new class called `PromptRegistry`.

https://github.com/CyR1en/CommandPrompter/blob/130dd29851f55a4736742d00755370d9844a819a/src/main/java/com/cyr1en/cp/CommandPrompter.java#L43-L46
