### ISSUE TITLE
CommandPrompt Bug w/ SuperVanish's Auto Vanish on Join

### ISSUE THREAD

**Issue by ItzFabb-uwu** [CyR1en/CommandPrompter#32]
# Content

 - CommandPrompt 
![image](https://github.com/CyR1en/CommandPrompter/assets/58950562/cea6de43-9f5f-4f76-963e-7f531eaaa7dd)

 - SuperVanish
![image](https://github.com/CyR1en/CommandPrompter/assets/58950562/35941726-2073-400d-9e03-df3d3dc7b5db)

Issue:
CommandPrompt is not liking the SuperVanish's Auto Vanish... 
![image](https://github.com/CyR1en/CommandPrompter/assets/58950562/b7aa0ba9-e2d0-47af-9f1b-398e00943d9c)

```
Server Version:
This server is running Paper version git-Paper-297 (MC: 1.20.2) (Implementing API version 1.20.2-R0.1-SNAPSHOT) (Git: 250388d)
You are 12 version(s) behind
Download the new version at: https://papermc.io/downloads/paper
```
```
[18:17:10 ERROR]: Could not pass event PlayerVanishStateChangeEvent to CommandPrompter v2.6.0
java.lang.NullPointerException: null
        at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:903) ~[guava-32.1.2-jre.jar:?]
        at com.google.common.cache.LocalCache$LocalManualCache.invalidate(LocalCache.java:4949) ~[guava-32.1.2-jre.jar:?]
        at com.cyr1en.commandprompter.prompt.ui.HeadCache.invalidate(HeadCache.java:60) ~[CommandPrompter-2.6.0-RELEASE.jar:?]
        at com.cyr1en.commandprompter.hook.hooks.VanishFallBack.onStateChange(VanishFallBack.java:29) ~[CommandPrompter-2.6.0-RELEASE.jar:?]
        at com.cyr1en.commandprompter.hook.hooks.SuperVanishHook.onVisibilityStateChange(SuperVanishHook.java:26) ~[CommandPrompter-2.6.0-RELEASE.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor884.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[paper-api-1.20.2-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:81) ~[paper-api-1.20.2-R0.1-SNAPSHOT.jar:git-Paper-297]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.20.2-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[paper-1.20.2.jar:git-Paper-297]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126) ~[paper-1.20.2.jar:git-Paper-297]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:615) ~[paper-api-1.20.2-R0.1-SNAPSHOT.jar:?]
        at de.myzelyam.supervanish.visibility.FileVanishStateMgr.setVanishedState(FileVanishStateMgr.java:41) ~[SuperVanish.jar:?]
        at de.myzelyam.supervanish.listeners.LoginListener.onLogin(LoginListener.java:46) ~[SuperVanish.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor138.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[paper-api-1.20.2-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:81) ~[paper-api-1.20.2-R0.1-SNAPSHOT.jar:git-Paper-297]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.20.2-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[paper-1.20.2.jar:git-Paper-297]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126) ~[paper-1.20.2.jar:git-Paper-297]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:615) ~[paper-api-1.20.2-R0.1-SNAPSHOT.jar:?]
        at net.minecraft.server.players.PlayerList.canPlayerLogin(PlayerList.java:763) ~[paper-1.20.2.jar:git-Paper-297]
        at net.minecraft.server.network.ServerLoginPacketListenerImpl.verifyLoginAndFinishConnectionSetup(ServerLoginPacketListenerImpl.java:218) ~[?:?]
        at net.minecraft.server.network.ServerLoginPacketListenerImpl.tick(ServerLoginPacketListenerImpl.java:86) ~[?:?]
        at net.minecraft.network.Connection.tick(Connection.java:592) ~[?:?]
        at net.minecraft.server.network.ServerConnectionListener.tick(ServerConnectionListener.java:240) ~[?:?]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1578) ~[paper-1.20.2.jar:git-Paper-297]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:446) ~[paper-1.20.2.jar:git-Paper-297]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1379) ~[paper-1.20.2.jar:git-Paper-297]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1156) ~[paper-1.20.2.jar:git-Paper-297]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:315) ~[paper-1.20.2.jar:git-Paper-297]
        at java.lang.Thread.run(Thread.java:840) ~[?:?]
```

**Comment by CyR1en** [comment]
Fixed with latest release https://github.com/CyR1en/CommandPrompter/releases/tag/2.7.0
