### ISSUE TITLE
org.bukkit.plugin.InvalidPluginException: Unsupported API version 1.15

### ISSUE THREAD

**Issue by CyR1en** [CyR1en/CommandPrompter#4]
```[12:33:07] [Server thread/ERROR]: Could not load 'plugins/CommandPrompter-0.1.17.jar' in folder 'plugins'
org.bukkit.plugin.InvalidPluginException: Unsupported API version 1.15
at org.bukkit.craftbukkit.v1_13_R2.util.CraftMagicNumbers.checkSupported(CraftMagicNumbers.java:226) ~[patched_1.13.2.jar:git-Paper-655]
at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:130) ~[patched_1.13.2.jar:git-Paper-655]
at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:334) ~[patched_1.13.2.jar:git-Paper-655]
at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:255) ~[patched_1.13.2.jar:git-Paper-655]
at org.bukkit.craftbukkit.v1_13_R2.CraftServer.loadPlugins(CraftServer.java:331) ~[patched_1.13.2.jar:git-Paper-655]
at net.minecraft.server.v1_13_R2.DedicatedServer.init(DedicatedServer.java:235) ~[patched_1.13.2.jar:git-Paper-655]
at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:787) ~[patched_1.13.2.jar:git-Paper-655]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_232]```

**Comment by CyR1en** [comment]
Fixed with https://github.com/CyR1en/CommandPrompter/commit/6913d89c59fe0fd827ddf62914c2f575ced99aef
