### ISSUE TITLE
[BUG] CommandPrompter does not support Minecraft version 1.21.1

### ISSUE THREAD

**Issue by PythonChicken123** [CyR1en/CommandPrompter#47]
## CommandPrompter does not support Minecraft 1.21.1
Minecraft 1.21.1 just released and this plugin does not support Minecraft server version 1.21.1. I have looked at the dev branch: https://ci.cyr1en.com/job/CommandPrompter/ and the latest build does not support Minecraft version 1.21.1

**Server Version:** Leaf 1.21.1
**Server JAR:** https://github.com/Winds-Studio/Leaf/releases/download/ver-1.21.1/leaf-1.21.1.jar
**Plugin Version:** CommandPrompter-2.9.0-shaded-36.jar
**Plugins:** (Some plugins don't work too because they are outdated)
```
[22:03:32 INFO]: [PluginInitializerManager] Paper plugins (1):
 - AdvancedKits (1.17.17)
[22:03:32 INFO]: [PluginInitializerManager] Bukkit plugins (74):
 - AdvancedChat (1.3.8), AdvancedCrates (4.0.10), AdvancedEnchantments (9.10.4), AntiPopup (9.2), BedrockParity (2.0.2), BetterRTP (3.6.13), BetterTeams (4.10.0), CMI (9.7.5.0), CMIEInjector (1.0.2.4), CMILib (1.5.1.1), CSuggestion (1.0.1), Chunky (1.4.10), ChunkyBorder (1.2.13), Citizens (2.0.35-SNAPSHOT (build 3493)), CommandPrompter (2.9.0), CustomFishing (2.2.16), DailyRewardsPlus (1.3.9), DecentHolograms (2.8.11), DeluxeCoinflip (2.7.13), DeluxeCombat (1.60.6), DeluxeMenus (1.14.1-DEV-183), DeluxeTags (1.8.3-DEV-23), DeluxeWithdraw (2024.07), DeluxeWithdrawLifestealCoreAddon (2024.07), FastAsyncWorldEdit (2.11.1-SNAPSHOT-871;fcbd346), FastTP (1.0), FasterCrystals (1.8.0), Geyser-Spigot (2.4.1-SNAPSHOT), HeadDatabase (4.19.8), ItemsAdder (4.0.2-alpha-test-3), JetsAntiAFKPro (3.8.4), KixsChatGames (2.1.7), LPX (3.4.8), LibsDisguises (10.0.44-SNAPSHOT), LifestealCore (2024.07-a), LightOptimizer (1.7), LiteBans (2.15.1), LoneLibs (1.0.56), LuckPerms (5.4.139), Matrix (7.9.21A), Multiverse-Core (4.3.12), NBTAPI (2.13.2), PinataParty (2.67.0), PlaceholderAPI (2.11.6), PlayerVaults (4.3.0), PremiumVanish (2.9.13), ProtocolLib (5.3.0-SNAPSHOT-726), RayTraceAntiXray (1.15.0), RoseLoot (1.2.17), ShopGUIPlus (1.97.1), SkBee (3.6.0), SkQuery (4.1.10), Skript (2.9.1), TAB (4.1.7), TimerFix (1.0), UltimateAutoRestart (2024.07), UpgradeableSpawners (4.14.6), Vault (1.7.3-CMI), ViaBackwards (5.0.2), ViaVersion (5.0.2), VirtualBounty (1.0), VoidGen (2.2.1), Votifier (2.7.3), Vulcan (2.9.0), WorldGuard (7.0.11-SNAPSHOT+2287-8ffc81a), WorldGuardExtraFlags (4.2.4-SNAPSHOT), WorldGuardRegionProtect (1.0.4.21), floodgate (2.2.3-SNAPSHOT (b109-49bd564)), packetevents (2.4.0), skRayFall (1.9.28), skript-placeholders (1.6.0), skript-reflect (2.5.1), zAuctionHouseV3 (3.2.2.3), zMenu (1.0.3.3)
```
**Spark Profiler:** https://spark.lucko.me/7LFDSiSWXl
**Spark Profiler 2 (Same Server):** https://spark.lucko.me/MAMI1lYD2e
**Stack Trace (Error):**
```
[22:07:52 INFO]: [CommandPrompter] Enabling CommandPrompter v2.9.0
[22:07:52 ERROR]: Error occurred while enabling CommandPrompter v2.9.0 (Is it up to date?)
com.cyr1en.commandapi.exceptions.UnsupportedVersionException: This version of Minecraft is unsupported: 1.21.1
        at CommandPrompter-2.9.0-shaded-36.jar/com.cyr1en.commandapi.CommandAPIVersionHandler.getPlatform(CommandAPIVersionHandler.java:71) ~[CommandPrompter-2.9.0-shaded-36.jar:?]
        at CommandPrompter-2.9.0-shaded-36.jar/com.cyr1en.commandapi.CommandAPI.onLoad(CommandAPI.java:103) ~[CommandPrompter-2.9.0-shaded-36.jar:?]
        at CommandPrompter-2.9.0-shaded-36.jar/com.cyr1en.commandprompter.commands.CommandAPIWrapper.load(CommandAPIWrapper.java:32) ~[CommandPrompter-2.9.0-shaded-36.jar:?]
        at CommandPrompter-2.9.0-shaded-36.jar/com.cyr1en.commandprompter.CommandPrompter.onEnable(CommandPrompter.java:82) ~[CommandPrompter-2.9.0-shaded-36.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:288) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:202) ~[leaf-1.21.1.jar:1.21.1-DEV-1a6df97]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:109) ~[leaf-1.21.1.jar:1.21.1-DEV-1a6df97]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:519) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.CraftServer.enablePlugin(CraftServer.java:658) ~[?:?]
        at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:607) ~[?:?]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:743) ~[leaf-1.21.1.jar:1.21.1-DEV-1a6df97]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:505) ~[leaf-1.21.1.jar:1.21.1-DEV-1a6df97]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:378) ~[leaf-1.21.1.jar:1.21.1-DEV-1a6df97]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1217) ~[leaf-1.21.1.jar:1.21.1-DEV-1a6df97]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:320) ~[leaf-1.21.1.jar:1.21.1-DEV-1a6df97]
        at java.base/java.lang.Thread.run(Thread.java:1575) ~[?:?]
[22:07:52 INFO]: [CommandPrompter] Disabling CommandPrompter v2.9.0
```

**Comment by DICEALPHAHU** [comment]
same problem, and waiting for new version
